language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.4
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=Django==1.8

install:
  - pip install -q $DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD python runtests.py

matrix:
    exclude:
        - python: 3.3
          env: DJANGO=Django==1.4
