language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.4.15
  - DJANGO=Django==1.5.10
  - DJANGO=Django==1.6.7

install:
  - pip install -q $DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD python dbpreferences/tests/run_tests.py

matrix:
    exclude:
        - python: 3.3
          env: DJANGO=Django==1.4.15
